#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""keep-1.9.0-1.0.6 add group to mysql table

Revision ID: 8c3927931920
Revises: d2ae31099d61
Create Date: 2019-01-22 20:52:49.624770

"""

# revision identifiers, used by Alembic.
revision = '8c3927931920'
down_revision = 'd2ae31099d61'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dag', sa.Column('groups', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('group', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group')
    op.drop_column('dag', 'groups')
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    # ### end Alembic commands ###
